server:
  port: 8080
---
spring:
  application:
    name: movie-service
  profiles:
    active: local
---
restClient:
  movie-info-service:
    url: http://localhost:8081/api/v1/movies/response-entity/getMovieInfo
  review-service:
    url: http://localhost:8082/api/v1/review/search


